(function() {

    'use strict';

    angular
        .module('ngClassifieds')
        .value('categories', [
            'Antiques',
            'Art',
            'Baby',
            'Books',
            'Business & Industrial',
            'Cameras & Photo',
            'Cell Phones & Accessories',
            'Clothing, Shoes & Accessories',
            'Coins & Paper Money',
            'Collectible',
            'Computers/Tablets & Networking',
            'Consumer Electronics',
            'Crafts',
            'Dolls & Bears',
            'DVDs & Movies',
            'Entertainment Memorabilia',
            'Everything Else',
            'Gift Cards & Coupons',
            'Health & Beauty',
            'Home & Garden',
            'Jewelry & Watches',
            'Music',
            'Musical Instruments & Gear',
            'Pet Supplies',
            'Pottery & Glass',
            'Real Estate',
            'Specialty Services',
            'Sporting Goods',
            'Sports Mem, Cards & Fan Shop',
            'Stamps',
            'Tickets & Experiences',
            'Toys & Hobbies',
            'Travel',
            'Video Games & Consoles'
        ])
        .value('states', [
            'AL',
            'AK',
            'AZ',
            'AR',
            'CA',
            'CO',
            'CT',
            'DE',
            'FL',
            'GA',
            'HI',
            'ID',
            'IL',
            'IN',
            'IA',
            'KS',
            'KY',
            'LA',
            'ME',
            'MD',
            'MA',
            'MI',
            'MN',
            'MS',
            'MO',
            'MT',
            'NE',
            'NV',
            'NH',
            'NJ',
            'NM',
            'NY',
            'NC',
            'ND',
            'OH',
            'OK',
            'OR',
            'PA',
            'RI',
            'SC',
            'SD',
            'TN',
            'TX',
            'UT',
            'VT',
            'VA',
            'WA',
            'WV',
            'WI',
            'WY'
        ])
})();
